### ISSUE TITLE
百度图片无法正常使用，可以提供详细信息吗？

### ISSUE THREAD

**Issue by jenkey2011** [itorr/baidu-images#1]
hi，看到描述 『极其偶尔在手机上用百度图片搜索时， 基础功能基本无法正常使用。』

请问有更详细的信息吗？
1. 系统平台 && 客户端
2. 图搜页面具体是哪个，可以直接贴地址
3. 基础功能指的是什么？

感谢

**Comment by itorr** [comment]
举个例子，iOS 上保存搜索到的图像。提示需要安装百度搜索 APP，装了 APP 从网页点击下载图像，依旧跳转到 AppStore。尝试利用当前 URL 启动 APP，只启动到 APP 首页、而不是具体搜索页。最终想要下载搜索到的图片需要开启 APP 从输入关键字开始完整的在 APP 上操作一遍才行。

而且在装了 百度搜索 APP 之后，在 iOS 上百度的手机网页会在几乎所有操作时都尝试跳转到 APP，并且大多数情况下只会跳转到 AppStore、即使已经安装了百度搜索 APP，剩下的情况下也只会启动APP 、而不是跳转到 APP 相对应手机网页的页面。

🤨不过我觉得这些也没必要问我了吧，用过一次都会遇到。

**Comment by jenkey2011** [comment]
好的感谢，我内部反馈下
