### ISSUE TITLE
关于获取图片的request请求URL

### ISSUE THREAD

**Issue by caichunjian520** [itorr/baidu-images#2]
根据代码，发送请求的URL是 
const uri = `${baseAPIURL}baidu/images?text=${encodeURIComponent(text)}&index=${index}&size=${size}`;

这个baseAPIURL是你的服务器hostname

那么有没有百度自己的URL请求API呢？还是只能用你这个URL？

**Comment by itorr** [comment]
加了个直接请求百度图片搜索 API 的例子，可以参考下
